feeds:
    - "https://dave.cheney.net/feed/atom"
    - "https://ieftimov.com/index.xml"
    - "https://blog.cloudflare.com/rss"
    - "http://feeds.feedburner.com/martinkl"
    - "https://research.swtch.com/feed.atom"
    - "https://martinfowler.com/feed.atom"
    - "https://www.ardanlabs.com/blog/index.xml"
    - "https://preshing.com/feed"
    - "https://eli.thegreenplace.net/feeds/all.atom.xml"
    - "https://distributed-computing-musings.com/feed"
    - "https://brooker.co.za/blog/atom.xml"
    - "https://thesquareplanet.com/feed.xml"
    - "https://rakyll.org/index.xml"
    - "https://sirupsen.com/atom.xml"
    - "https://go.dev/blog/feed.atom"
    - "https://benhoyt.com/writings/rss.xml"
    - "http://journal.stuffwithstuff.com/atom.xml"
    - "https://jvns.ca/atom.xml"
    - "https://notes.eatonphil.com/rss.xml"
    - "https://grafana.com/categories/engineering/index.xml"
    - "https://www.calhoun.io/post/rss/index.xml"
    - "http://morsmachine.dk/feed.atom"
    - "https://samwho.dev/rss.xml"
    - "https://www.uber.com/blog/engineering/backend/rss/"
    - "https://bbengfort.github.io/index.xml"
    - "https://planetscale.com/blog/rss.xml"
    - "https://antonz.org/index.xml"
    - "https://appliedgo.net/index.xml"
    - "https://thorstenball.com/atom.xml"
    - "https://registerspill.thorstenball.com/feed"
    - "https://xeiaso.net/blog.rss"
    - "https://commaok.xyz/index.xml"
    - "https://blog.merovius.de/atom.xml"
    - "https://crawshaw.io/atom.xml"
    - "https://johnnysswlab.com/feed/"
    - "https://fasterthanli.me/index.xml"
    - "https://threedots.tech/index.xml"
    - "https://www.alexedwards.net/static/feed.rss"
    - "https://commandcenter.blogspot.com/feeds/posts/default"
    - "https://tailscale.com/blog/index.xml"
    - "https://mitchellh.com/feed.xml"
    - "https://npf.io/blog/index.xml"
    - "https://golangweekly.com/rss/"
    - "https://carlosbecker.com/posts/index.xml"
    - "https://jbrandhorst.com/posts/index.xml"
    - "https://bitfieldconsulting.com/posts?format=rss"
    - "https://trstringer.com/feed.xml"
    - "https://hesec.de/posts/index.xml"
    - "https://blog.kowalczyk.info/atom.xml"
    - "https://brandur.org/articles.atom"
    - "https://boyter.org/index.xml"
    - "https://highscalability.com/rss/"
    - "https://fly.io/blog/feed.xml"
    - "https://blog.questionable.services/atom.xml"
    - "https://encore.dev/rss/atom.xml"
    - "https://iximiuz.com/feed.atom"
    - "https://ops.tips/index.xml"
    - "https://ianlopshire.com/rss/"
    - "https://philpearl.github.io/index.xml"
    - "https://rauljordan.com/rss.xml"
    - "https://cep.dev/posts/index.xml"
    - "https://savo.la/atom.xml"
    - "https://unskilled.blog/index.xml"
    - "https://matttproud.com/blog/index.xml"
    - "https://feeds.feedburner.com/felixge"
    - "https://victoriametrics.com/index.xml"
    - "https://konradreiche.com/blog/index.xml"
    - "https://mliezun.github.io/feed.xml"
    - "https://brooker.co.za/blog/atom.xml"
    - "https://www.willem.dev/articles/index.xml"
    - "https://rednafi.com/index.xml"
    - "https://mcyoung.xyz"
    - "https://www.jvt.me/feed.xml"
    - "https://www.jvt.me/kind/articles/feed.xml"

emails:
    - "denpeshkov98@gmail.com"
